### Test grantRole con ruolo admin per address#1 lowercase
POST http://localhost:3000/roles/grant
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZGRyZXNzIjoiMHhmMzlGZDZlNTFhYWQ4OEY2RjRjZTZhQjg4MjcyNzljZmZGYjkyMjY2Iiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzU0MzkxNjg1LCJleHAiOjE3NTQzOTUyODV9.QCqHBsRGhKdYxN85YJAstykrNoWpLyTNBNqAcTW4w8U
Content-Type: application/json

{
  "role": "CERTIFICATORE_ROLE",
  "target": "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
}

